### ISSUE TITLE
Support IPv6 on Hetzner

### ISSUE THREAD

**Issue by 0x221A** [coreos/afterburn#1141]
# Feature Request #

Afterburn currently supports only IPv4 for Hetzner. IPv6 metadata can be retrieved from Hetzner's API endpoints (`/hetzner/v1/metadata` or `/hetzner/v1/metadata/network-config`) in the `network-config.config[0].subnets[n]` property, where `ipv6` is set to `true`.

## Environment ##

Hetzner

## Desired Feature ##

Enable Afterburn to configure IPv6 automatically on server startup.

## Other Information ##

- If no public network is configured, the config property in network-config will be an empty array.
- An example value of the `network-config` field is shown below.
```
network-config:
  config:
  - mac_address: <redacted>
    name: eth0
    subnets:
    - ipv4: true
      type: dhcp
    - address: 2a01:<redacted>::1/64
      dns_nameservers:
      - 2a01:4ff:ff00::add:1
      - 2a01:4ff:ff00::add:2
      gateway: fe80::1
      ipv6: true
      type: static
    type: physical
  version: 1
```
